version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - PG_DATA=${PG_DATA}
    ports:
      - target: 5432
        published: 25432
        mode: host
    command: postgres -c 'max_connections=500'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net

  cache:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
     - cache:/data
    networks:
      - net
  
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - db
      - cache
    

networks:
  net:
    driver: bridge

volumes:
  cache:
    driver: local